import React, { useState, useEffect } from 'react';
import { onSnapshot, collection, query, doc } from 'firebase/firestore';
import { signInAnonymously } from 'firebase/auth';
import { auth, db } from './firebase';

import Header from './components/Header';
import StorySection from './components/StorySection';
import FAQ from './components/FAQ';
import ProgressSection from './components/ProgressSection';
import DonationForm from './components/DonationForm';
import SupportersList from './components/SupportersList';
import PaymentModal from './components/PaymentModal';
import AdminModal from './components/AdminModal';
import Toast from './components/Toast';

export default function App() {
  const [targetAmount, setTargetAmount] = useState(50000);
    const [donations, setDonations] = useState([]);
      const [totalRaised, setTotalRaised] = useState(0);
        
          const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
            const [isAdminModalOpen, setIsAdminModalOpen] = useState(false);
              const [pendingDonation, setPendingDonation] = useState(null);
                
                  const [toast, setToast] = useState({ show: false, message: '', isSuccess: true });

                    useEffect(() => {
                        signInAnonymously(auth).catch(console.error);

                            const unsubConfig = onSnapshot(doc(db, 'settings', 'config'), (docSnap) => {
                                  if (docSnap.exists() && docSnap.data().targetAmount) {
                                          setTargetAmount(docSnap.data().targetAmount);
                                                }
                                                    });

                                                        const unsubDonations = onSnapshot(query(collection(db, 'donations')), (snapshot) => {
                                                              let total = 0;
                                                                    let list = [];
                                                                          snapshot.forEach(doc => {
                                                                                  let data = doc.data();
                                                                                          let amt = Number(data.amount) || 0;
                                                                                                  total += amt;
                                                                                                          list.push({ id: doc.id, ...data });
                                                                                                                });
                                                                                                                      list.sort((a, b) => (Number(b.timestamp) || 0) - (Number(a.timestamp) || 0));
                                                                                                                            setDonations(list);
                                                                                                                                  setTotalRaised(total);
                                                                                                                                      });

                                                                                                                                          return () => {
                                                                                                                                                unsubConfig();
                                                                                                                                                      unsubDonations();
                                                                                                                                                          };
                                                                                                                                                            }, []);

                                                                                                                                                              const showToast = (message, isSuccess = true) => {
                                                                                                                                                                  setToast({ show: true, message, isSuccess });
                                                                                                                                                                      setTimeout(() => setToast({ show: false, message: '', isSuccess: true }), 3500);
                                                                                                                                                                        };

                                                                                                                                                                          const handleInitiateDonation = (data) => {
                                                                                                                                                                              setPendingDonation(data);
                                                                                                                                                                                  setIsPaymentModalOpen(true);
                                                                                                                                                                                    };

                                                                                                                                                                                      return (
                                                                                                                                                                                          <div className="text-slate-800 antialiased pb-12 font-[Poppins] bg-[#f8fafc] min-h-screen">
                                                                                                                                                                                                <Header onAdminClick={() => setIsAdminModalOpen(true)} />

                                                                                                                                                                                                      <main className="max-w-5xl mx-auto px-4 mt-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
                                                                                                                                                                                                              <div className="lg:col-span-7 space-y-6">
                                                                                                                                                                                                                        <StorySection />
                                                                                                                                                                                                                                  <FAQ />
                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                  <div className="lg:col-span-5">
                                                                                                                                                                                                                                                            <div className="bg-white rounded-2xl shadow-xl border border-slate-100 p-6 md:p-8 sticky top-24">
                                                                                                                                                                                                                                                                        <ProgressSection 
                                                                                                                                                                                                                                                                                      totalRaised={totalRaised} 
                                                                                                                                                                                                                                                                                                    targetAmount={targetAmount} 
                                                                                                                                                                                                                                                                                                                  donorCount={donations.length} 
                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                          <hr className="my-6 border-slate-100" />
                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-xl font-bold mb-4 text-slate-800">Support the Setup</h3>
                                                                                                                                                                                                                                                                                                                                                                  <DonationForm onInitiate={handleInitiateDonation} />
                                                                                                                                                                                                                                                                                                                                                                              <SupportersList donations={donations} />
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                      </main>

                                                                                                                                                                                                                                                                                                                                                                                                            {isPaymentModalOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                    <PaymentModal 
                                                                                                                                                                                                                                                                                                                                                                                                                              pendingDonation={pendingDonation} 
                                                                                                                                                                                                                                                                                                                                                                                                                                        onClose={() => setIsPaymentModalOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  showToast={showToast}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isAdminModalOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AdminModal 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClose={() => setIsAdminModalOpen(false)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        donations={donations}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalRaised={totalRaised}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            targetAmount={targetAmount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      showToast={showToast}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Toast toast={toast} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }