name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: beyond-the-verse

      - name: Build
        # 🌟 यहाँ हमने Secrets को Build step के साथ जोड़ दिया है
        run: npm run build
        working-directory: beyond-the-verse
        env:
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_DICT_API_KEY: ${{ secrets.DICT_API_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'beyond-the-verse/dist/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
